### ISSUE TITLE
FIngenieraSoftware_U3_Practica de Requisitos

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/practica-de-requisitos-systems#1]

**Comment by kirus21** [comment]
cal: 23%

**Comment by KarlaV0** [comment]
Puedes subir la rubrica,por favor

**Comment by KarlaV0** [comment]
[FIngenieraSoftware_U3_Practica de Requisitos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-requisitos-systems/files/7599026/FIngenieraSoftware_U3_Practica.de.Requisitos.pdf)
