### ISSUE TITLE
 PRACTICA DE REQUISITOS

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/practica-de-requisitos-systems#2]
[FIngenieraSoftware_U3_Practica de Requisitos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-requisitos-systems/files/7599027/FIngenieraSoftware_U3_Practica.de.Requisitos.pdf)

**Comment by Yabin-2021** [comment]
Anexo evaluación:

[7. Evaluación reporte de practica Entrevista.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-requisitos-systems/files/7599091/7.Evaluacion.reporte.de.practica.Entrevista.pdf)

Calificación:

**28.5 %**

Nota: La ambigüedad que se menciona en la evaluación, se refiere a que no necesariamente se necesitan imágenes en una entrevista.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
